# fly.toml app configuration file generated for fin-app-vk on 2023-05-10T20:01:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fin-app-vk"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
